export type Question = {
  id: number;
  category: "campeao" | "macro" | "micro" | "itens" | "objetivo";
  difficulty: "bronze";
  question: string;
  image?: string;
  options: string[];
  correct: number;
  explanation: string;
};

export const questions: Question[] = [
  // CAMPEÕES
  {
    id: 1,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ultimate do Galio faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg",
    options: [
      "Voa até um aliado no mapa inteiro e cai causando knock-up em área",
      "Cria um escudo gigante que bloqueia habilidades inimigas",
      "Lança uma onda de força em linha reta",
      "Invoca pedras do céu em uma área",
    ],
    correct: 0,
    explanation: "Hero's Entrance: Galio voa até um aliado em qualquer lugar do mapa e cai com impacto, causando knock-up nos inimigos próximos.",
  },
  {
    id: 2,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a ultimate da Katarina?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg",
    options: [
      "Lança uma corrente de facas em linha reta",
      "Teleporta para o inimigo mais próximo instantaneamente",
      "Gira lançando facas em vários inimigos próximos — qualquer CC interrompe",
      "Fica invisível e acumula dano para o próximo ataque",
    ],
    correct: 2,
    explanation: "Death Lotus: Katarina gira atirando facas em até 3 inimigos. Qualquer CC a interrompe — é o maior ponto fraco dela!",
  },
  {
    id: 3,
    category: "campeao",
    difficulty: "bronze",
    question: "O que o Malphite faz com a sua ultimate?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg",
    options: [
      "Cria um escudo de pedra ao redor de si mesmo",
      "Lança pedras em todos os inimigos visíveis",
      "Vira invencível e regenera HP por 3 segundos",
      "Salta em alta velocidade e causa knock-up em área ao cair",
    ],
    correct: 3,
    explanation: "Unstoppable Force: Malphite salta em direção a um ponto causando knock-up massivo. Uma das melhores ults para iniciar teamfights!",
  },
  {
    id: 4,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a passiva do Yasuo?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
    options: [
      "Dobra o bônus de crítico mas acumula escudo ao se mover",
      "Cura ao matar inimigos com ataques básicos",
      "Aumenta velocidade de movimento após cada kill",
      "Reduz o cooldown das habilidades ao dar golpes críticos",
    ],
    correct: 0,
    explanation: "Way of the Wanderer: Yasuo tem o bônus de crítico dobrado (os itens custam o dobro) e acumula um escudo (Resolve) conforme se move.",
  },
  {
    id: 5,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a Lux faz com sua ultimate?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg",
    options: [
      "Cura todos os aliados próximos com luz",
      "Cria um campo de luz que lentifica inimigos por 3 segundos",
      "Dispara um laser enorme em linha reta com muito alcance",
      "Revela todos os inimigos no mapa por 5 segundos",
    ],
    correct: 2,
    explanation: "Final Spark: Lux dispara um laser gigante em linha reta. Tem alcance enorme e cooldown baixo graças à passiva.",
  },
  {
    id: 6,
    category: "campeao",
    difficulty: "bronze",
    question: "O Zed é bom contra qual tipo de campeão?",
    options: [
      "Tanques com muita armadura e HP",
      "Suportes com habilidades de cura",
      "ADCs com Thornmail construído",
      "Magos e carries AP com pouca vida",
    ],
    correct: 3,
    explanation: "Zed é um assassino AD — destrói magos e carries AP que não têm vida. Contra tanques ele é muito fraco por não ter dano de penetração de armadura.",
  },
  {
    id: 7,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ult da Renata Glasc faz nos inimigos que acerta?",
    options: [
      "Eles ficam em frenesi e atacam os próprios aliados por alguns segundos",
      "Eles ficam enraizados no lugar por 2 segundos",
      "Eles perdem toda a visão de mapa temporariamente",
      "Eles são empurrados em direção à base inimiga",
    ],
    correct: 0,
    explanation: "Hostile Takeover: os inimigos atingidos entram em frenesi e atacam os próprios aliados. Se pegar o carry inimigo, ele literalmente mata o próprio time!",
  },
  {
    id: 8,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a função dos cogumelos invisíveis do Teemo?",
    options: [
      "Curar aliados que passam por cima deles",
      "Bloquear o caminho de inimigos na jungle",
      "Envenenar e lentificar inimigos que pisam, dando visão da área",
      "Explodir causando dano em área quando um aliado chega perto",
    ],
    correct: 2,
    explanation: "Noxious Trap: ficam invisíveis, causam dano + lentidão nos inimigos e dão visão da área. Ótimos para warding e controle de mapa.",
  },

  // MACRO
  {
    id: 9,
    category: "macro",
    difficulty: "bronze",
    question: "Você acabou de matar o Dragon. O que fazer LOGO EM SEGUIDA?",
    options: [
      "Voltar para a base para comprar itens",
      "Empurrar a lane mais próxima ou forçar outro objetivo",
      "Esperar o respawn do próximo drag",
      "Ficar no pit aguardando o inimigo passar",
    ],
    correct: 1,
    explanation: "Após pegar objetivo, converta a vantagem numérica — empurre torre, pegue Rift Herald ou force o próximo objetivo. Não desperdice o timing!",
  },
  {
    id: 10,
    category: "macro",
    difficulty: "bronze",
    question: "O que é 'push' de wave?",
    options: [
      "Empurrar os minions em direção à torre inimiga",
      "Recuar para a torre aliada com os minions",
      "Matar os minions da jungle para ganhar XP extra",
      "Usar habilidades em área para curar a wave aliada",
    ],
    correct: 0,
    explanation: "Push é empurrar os minions em direção ao inimigo/torre dele. Cria pressão de mapa e libera você para rotar ou fazer objetivos.",
  },
  {
    id: 11,
    category: "macro",
    difficulty: "bronze",
    question: "Qual objetivo dá o buff mais poderoso do late game?",
    options: [
      "Dragão Ancião",
      "Rift Herald",
      "Baron Nashor",
      "Torre inimiga",
    ],
    correct: 2,
    explanation: "Baron Nashor dá Hand of Baron para os aliados vivos, fortalecendo os minions aliados massivamente. É o objetivo decisivo para fechar o jogo!",
  },
  {
    id: 12,
    category: "macro",
    difficulty: "bronze",
    question: "Dois inimigos desapareceram do mapa (MIA). Você está sozinho na bot lane. O que fazer?",
    options: [
      "Continuar farmando — provavelmente foram pra base",
      "Recuar para a torre e pingar missing para o time",
      "Avançar e pressionar a torre inimiga rapidamente",
      "Ir ao rio checar se estão no drag",
    ],
    correct: 1,
    explanation: "Quando inimigos somem, sempre recue e avise o time com ping. Continuar exposto é pedir para levar um gank grátis.",
  },
  {
    id: 13,
    category: "macro",
    difficulty: "bronze",
    question: "Quando é o momento certo para dar recall (B)?",
    options: [
      "Somente quando a wave estiver perdida para o inimigo",
      "Apenas após matar o inimigo da sua lane",
      "Quando tiver HP/mana baixo ou ouro suficiente para um item importante",
      "Nunca — sair da lane é sempre errado",
    ],
    correct: 2,
    explanation: "Recall quando estiver com HP/mana baixo ou com ouro para um item importante, e sempre com a lane empurrada para não perder minions.",
  },
  {
    id: 14,
    category: "macro",
    difficulty: "bronze",
    question: "O que é 'roaming' e quem costuma fazer?",
    options: [
      "Defender a jungle aliada — geralmente o jungler",
      "Farmar toda a wave rapidamente — geralmente o ADC",
      "Ficar na lane e conter o inimigo — geralmente o top",
      "Sair da lane para ajudar outras rotas — geralmente mid ou support",
    ],
    correct: 3,
    explanation: "Roaming é deixar temporariamente a sua lane para criar vantagem em outra parte do mapa. Mid laner e support são os que mais fazem isso.",
  },
  {
    id: 15,
    category: "macro",
    difficulty: "bronze",
    question: "Você tem 1500 de ouro e o item principal custa 3200. O que fazer?",
    options: [
      "Comprar um componente agora e voltar mais tarde com o resto",
      "Ficar na lane farmando até juntar o valor total",
      "Não comprar nada e guardar o ouro para o item completo",
      "Vender itens antigos para comprar o item caro logo",
    ],
    correct: 0,
    explanation: "Sempre compre componentes para ter power spikes durante o jogo. Ficar sem item enquanto o inimigo já completou o dele é uma enorme desvantagem.",
  },

  // MICRO
  {
    id: 16,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'CS' ou 'last hit'?",
    options: [
      "Matar um campeão inimigo com o último golpe para roubar a kill",
      "Dar o golpe final em um minion para receber o ouro dele",
      "Usar a última habilidade disponível antes de recuar",
      "Atacar a torre com o último minion vivo da wave",
    ],
    correct: 1,
    explanation: "CS (Creep Score) é dar o último golpe no minion para receber o ouro. É a base do farming — um bom CS no early game compra itens mais rápido.",
  },
  {
    id: 17,
    category: "micro",
    difficulty: "bronze",
    question: "Para que serve o Flash?",
    options: [
      "Aumentar a velocidade de movimento por 2 segundos",
      "Causar dano em área ao redor do personagem",
      "Curar 15% do HP máximo instantaneamente",
      "Teleporte rápido de curto alcance em qualquer direção",
    ],
    correct: 3,
    explanation: "Flash é o spell mais importante do jogo — serve para escapar, engajar, passar por paredes ou se reposicionar instantaneamente.",
  },
  {
    id: 18,
    category: "micro",
    difficulty: "bronze",
    question: "O que acontece se você ficar parado no alcance de uma torre inimiga?",
    options: [
      "Nada — a torre só ataca se você atacar alguém primeiro",
      "A torre ataca você automaticamente após um aviso visual",
      "Você fica lento mas não recebe dano",
      "A torre te cura se você for aliado",
    ],
    correct: 1,
    explanation: "Torres atacam automaticamente qualquer inimigo no alcance. Fique fora do range da torre a menos que seja seguro avançar.",
  },
  {
    id: 19,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'kiting'?",
    options: [
      "Atacar e se mover alternadamente para causar dano mantendo distância",
      "Ficar parado e soltar toda a combo de habilidades de uma vez",
      "Usar um aliado como escudo humano durante a luta",
      "Recuar para a torre arrastando o inimigo para dentro do range dela",
    ],
    correct: 0,
    explanation: "Kiting é atacar-mover-atacar para manter distância. Essencial para ADCs e carries que precisam sobreviver enquanto causam dano.",
  },
  {
    id: 20,
    category: "micro",
    difficulty: "bronze",
    question: "Qual é a função principal do Ignite?",
    options: [
      "Curar o aliado mais próximo de você",
      "Revelar inimigos invisíveis na área",
      "Causar dano e reduzir a cura do inimigo para finalizar kills",
      "Lentificar o inimigo para facilitar fuga",
    ],
    correct: 2,
    explanation: "Ignite causa dano true damage, aplica Grievous Wounds (reduz cura) e serve para finalizar inimigos que fugiriam com pouco HP.",
  },
  {
    id: 21,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'poke'?",
    options: [
      "Engajar em cima do inimigo com habilidades de curto alcance",
      "Usar a jungle para emboscar inimigos pela lateral",
      "Chamar o jungler toda vez que o inimigo se aproximar",
      "Acertar habilidades de longo alcance para desgastar o inimigo sem engajar",
    ],
    correct: 3,
    explanation: "Poke é desgastar o inimigo com habilidades seguras de longo alcance sem se comprometer em uma luta completa. Lux, Ezreal e Jayce são exemplos clássicos.",
  },
  {
    id: 22,
    category: "micro",
    difficulty: "bronze",
    question: "Você está com 20% de HP na lane. Qual a atitude certa?",
    options: [
      "Continuar atacando pois está com vantagem de CS",
      "Recuar para a torre ou dar recall para não morrer de graça",
      "Dar all-in no inimigo pois ele não espera",
      "Pedir gank ao jungler e continuar na mesma posição",
    ],
    correct: 1,
    explanation: "Com pouco HP você é alvo fácil para gank. Priorize sobrevivência — uma morte grátis dá ouro e vantagem ao inimigo.",
  },

  // ITENS
  {
    id: 23,
    category: "itens",
    difficulty: "bronze",
    question: "Qual é a função do Thornmail?",
    options: [
      "Aumentar seu dano mágico em porcentagem",
      "Dar velocidade de movimento extra ao correr",
      "Refletir dano físico para atacantes e aplicar Grievous Wounds neles",
      "Curar o portador a cada segundo durante a luta",
    ],
    correct: 2,
    explanation: "Thornmail reflete dano físico e aplica Grievous Wounds em quem te ataca. Perfeito contra ADCs e campeões com muito life steal.",
  },
  {
    id: 24,
    category: "itens",
    difficulty: "bronze",
    question: "Quando você deve comprar itens com Grievous Wounds?",
    options: [
      "Sempre como primeiro item em qualquer partida",
      "Quando o time inimigo tem muita cura (Soraka, Mundo, Aatrox...)",
      "Somente quando você for suporte",
      "Apenas no late game após completar dois itens principais",
    ],
    correct: 1,
    explanation: "Grievous Wounds reduz a cura em 40-60%. É essencial quando o inimigo tem campeões de muita cura como Soraka, Mundo, Aatrox ou Sylas.",
  },
  {
    id: 25,
    category: "itens",
    difficulty: "bronze",
    question: "O que o Rabadon's Deathcap faz?",
    options: [
      "Reduz o cooldown de todas as habilidades em 20%",
      "Aumenta a cura e o escudo de habilidades em 35%",
      "Dá penetração mágica para atravessar a resistência mágica inimiga",
      "Aumenta TODO o seu AP acumulado em 35%",
    ],
    correct: 3,
    explanation: "Rabadon's amplifica todo o seu AP em 35%. É o item mais poderoso para magos no late game — faz o dano explodir.",
  },

  // OBJETIVOS
  {
    id: 26,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que é um 'gank' do jungler?",
    options: [
      "O jungler farmar os camps da jungle inimiga",
      "O jungler voltar para base para recuperar HP",
      "O jungler visitar uma lane para ajudar a matar um inimigo",
      "O jungler roubar o objetivo enquanto o inimigo está distraído",
    ],
    correct: 2,
    explanation: "Gank é quando o jungler vem até a sua lane criando superioridade numérica (2v1 ou 3v2) para tentar matar o inimigo.",
  },
  {
    id: 27,
    category: "objetivo",
    difficulty: "bronze",
    question: "Qual é a diferença entre Dragon e Baron Nashor?",
    options: [
      "Dragon dá buffs elementais acumuláveis (bot side); Baron fortalece minions (top side)",
      "Não há diferença — os dois dão o mesmo tipo de buff para o time",
      "Dragon aparece no top e Baron no bot do mapa",
      "Baron é mais fácil de matar e Dragon é o objetivo mais forte do jogo",
    ],
    correct: 0,
    explanation: "Dragon (bot) dá buffs elementais que acumulam. Baron (top) dá Hand of Baron que fortalece minions. Ambos são cruciais em momentos diferentes.",
  },
  {
    id: 28,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que acontece quando você destrói o Nexus inimigo?",
    options: [
      "O jogo termina com vitória para o seu time imediatamente",
      "Você ganha 1000 de ouro extra para todos os aliados",
      "O inimigo perde 1 vida e o mapa reinicia",
      "Você pode invocar um campeão extra por 30 segundos",
    ],
    correct: 0,
    explanation: "Destruir o Nexus é o objetivo FINAL do jogo. Assim que cai, a partida termina — é por isso que tudo no jogo gira em torno de abrir caminho até ele.",
  },
  {
    id: 29,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que é 'freeze' de wave?",
    options: [
      "Usar campeões de gelo para lentificar a wave inimiga",
      "Empurrar todos os minions rápido para a torre inimiga",
      "Usar habilidades de slow nos minions inimigos",
      "Manter a wave equilibrada perto da sua torre para negar farm ao inimigo",
    ],
    correct: 3,
    explanation: "Freeze é deixar a wave estacionada perto da sua torre. O inimigo não consegue farmar sem se expor ao alcance da torre — poderosa ferramenta de lane.",
  },
  {
    id: 30,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que significa 'splitpush'?",
    options: [
      "Dividir o time ao meio para atacar duas torres ao mesmo tempo",
      "Um jogador empurrar uma lane sozinho enquanto o time pressiona outro lado",
      "Recuar todo o time para a base simultaneamente",
      "Atacar o Baron e o Dragon ao mesmo tempo com divisão do time",
    ],
    correct: 1,
    explanation: "Splitpush é quando um campeão forte (Fiora, Tryndamere, Jax) pressiona sozinho, forçando inimigos a responder enquanto o time faz objetivos.",
  },
  {
    id: 31,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a Jinx ganha ao participar de uma kill ou destruir um objetivo?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
    options: [
      "Um escudo que absorve o próximo dano recebido",
      "Mana recuperada instantaneamente para continuar lutando",
      "Grande aumento de velocidade de movimento e de ataque (Get Excited!)",
      "Teleporte automático para perto do aliado mais próximo",
    ],
    correct: 2,
    explanation: "Get Excited! (passiva): ao participar de kill ou destruir objetivo, Jinx recebe enorme boost de velocidade. É por isso que ela é tão difícil de escapar em teamfights quando começa a snowball.",
  },
  {
    id: 32,
    category: "macro",
    difficulty: "bronze",
    question: "Seu time ganhou um teamfight 5x5. Qual é o ERRO mais clássico do Bronze?",
    options: [
      "Ir direto para o Baron ou torres após a luta",
      "Ficar parado comemorando até os inimigos respawnarem",
      "Dar recall para comprar itens enquanto tem vantagem",
      "Separar o time para pressionar múltiplas lanes",
    ],
    correct: 1,
    explanation: "O erro clássico do Bronze: ficar 'dançando' em cima dos cadáveres em vez de converter a vantagem em objetivos. USE o tempo de respawn dos inimigos!",
  },
  // CAMPEÕES NOVOS — teamfight e objetivos
  {
    id: 33,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ult da Ashe faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg",
    options: [
      "Dispara uma flecha global que atordoa o primeiro inimigo que acertar",
      "Cria uma chuva de flechas em área",
      "Aumenta o alcance de ataque de todos os aliados",
      "Lança uma flecha que retorna e acerta dois inimigos",
    ],
    correct: 0,
    explanation: "Crystal Arrow: flecha global que atordoa (stun) o primeiro inimigo atingido — quanto maior a distância, maior a duração do stun. Ótima para iniciar de longe!",
  },
  {
    id: 34,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ult da Miss Fortune faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg",
    options: [
      "Teleporta para o inimigo mais próximo e causa dano ponto a ponto",
      "Dispara um cone de balas causando dano massivo em área — pode ser interrompida por CC",
      "Aumenta velocidade de ataque de todos os aliados próximos",
      "Lança uma bomba que explode após 2 segundos numa área",
    ],
    correct: 1,
    explanation: "Bullet Time: MF metrálha em cone causando enorme dano. É cancelada por CC, então use em inimigos presos (Amumu, Nautilus, etc.) para maximizar o dano!",
  },
  {
    id: 35,
    category: "campeao",
    difficulty: "bronze",
    question: "O que o Sett faz com a sua ultimate?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg",
    options: [
      "Bate no chão causando knock-up em todos próximos",
      "Cria um escudo enorme que bloqueia projéteis",
      "Agarra um campeão inimigo e o joga sobre os outros inimigos causando dano em área",
      "Pula sobre um inimigo e o derruba no chão por 1 segundo",
    ],
    correct: 2,
    explanation: "The Show Stopper: Sett agarra um inimigo (geralmente o carry ou tank deles) e o arremessa sobre os demais causando dano em área. Ótimo para dividir o time inimigo!",
  },
  {
    id: 36,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a característica mais especial da Mel em combate?",
    options: [
      "Ela se torna invisível quando recebe muito dano seguido",
      "Ela cura todos os aliados próximos ao usar habilidades",
      "Ela pode refletir habilidades inimigas de volta para quem as lançou",
      "Ela cria cópias de si mesma para confundir o inimigo",
    ],
    correct: 2,
    explanation: "Mel pode refletir habilidades inimigas de volta ao lançador — inclusive ults poderosas. Saber o timing certo do reflect é o que separa uma Mel boa de uma ruim!",
  },
  {
    id: 37,
    category: "campeao",
    difficulty: "bronze",
    question: "Como funciona a passiva do Braum?",
    options: [
      "Ele regenera HP toda vez que um aliado usa uma habilidade",
      "Aliados que acertam um inimigo marcado pelo Braum acumulam stacks — no 4º stack o inimigo leva stun",
      "Cada ataque básico do Braum reduz a armadura do inimigo",
      "Ele reflete dano para inimigos que o atacam na frente",
    ],
    correct: 1,
    explanation: "Concussive Blows: após Braum aplicar a marca, qualquer aliado que bater no inimigo acumula stacks. No 4º hit o inimigo é atordoado. Coordenação com o time é tudo!",
  },
  {
    id: 38,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ult do Nautilus faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg",
    options: [
      "Naultilus mergulha e reaparece embaixo de um inimigo",
      "Cria um campo de pressão de água que lentifica todos ao redor",
      "Lança uma âncora que puxa todos os inimigos para o centro",
      "Lança uma onda que vai até o alvo causando knock-up em cadeia nos inimigos pelo caminho",
    ],
    correct: 3,
    explanation: "Depth Charge: dispara no alvo e vai causando knock-up em cada inimigo pelo caminho. O alvo final fica stunado. Perfeita para iniciar teamfights!",
  },
  {
    id: 39,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ult do Amumu faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg",
    options: [
      "Causa dano em área ao redor dele em linha reta",
      "Enraíza e silencia todos os inimigos próximos em área",
      "Aumenta o dano de todos os aliados próximos por 3 segundos",
      "Puxa todos os inimigos do mapa para perto de si",
    ],
    correct: 1,
    explanation: "Curse of the Sad Mummy: enraíza TODOS os inimigos em área ao redor do Amumu. Combinado com Miss Fortune, Jinx ou Katarina vira um teamfight impossível de escapar!",
  },
  {
    id: 40,
    category: "objetivo",
    difficulty: "bronze",
    question: "Em um teamfight você é o ADC. Quem você deve focar primeiro?",
    options: [
      "O tank inimigo pois ele está na sua frente",
      "O campeão mais próximo de você para limpar rápido",
      "O carry ou mago inimigo — quem causa mais dano para o seu time",
      "O suporte inimigo para ele não poder curar o time deles",
    ],
    correct: 2,
    explanation: "Como ADC, sempre foque o carry mais ameaçador — o mago, ADC ou assassino inimigo. Ficar atacando o tank é jogar dano no lixo.",
  },
  {
    id: 41,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que significa 'peel' no contexto de um teamfight?",
    options: [
      "Fugir da luta quando estiver com pouco HP",
      "Proteger o seu carry usando CC e habilidades de suporte nos inimigos que o ameaçam",
      "Iniciar a luta pulando em cima do carry inimigo",
      "Dar dano em área para acertar o máximo de inimigos possível",
    ],
    correct: 1,
    explanation: "Peel é proteger seu carry — usar slows, stuns e knockbacks nos inimigos que tentam chegar nele. Braum, Lulu e Janna são campeões feitos para isso.",
  },
  {
    id: 42,
    category: "objetivo",
    difficulty: "bronze",
    question: "Qual é a ordem de prioridade correta de objetivos no mid game?",
    options: [
      "Baron → Dragon → Torres → Kills",
      "Torres → Dragon → Baron → Kills",
      "Dragon e Rift Herald (early) → Torres → Baron (late)",
      "Kills → Baron → Torres → Dragon",
    ],
    correct: 2,
    explanation: "Early game: Dragon e Rift Herald. Com Herald você destrói torres. Com torres você controla mapa. Com mapa você faz Baron. Com Baron você fecha o jogo!",
  },
  // POSICIONAMENTO E ROLES
  {
    id: 43,
    category: "micro",
    difficulty: "bronze",
    question: "Você é o ADC no teamfight. Onde deve se posicionar?",
    options: [
      "Na frente com o tank para causar mais dano",
      "No meio do grupo para não ficar sozinho",
      "Atrás de todos, fora do alcance dos inimigos, causando dano de longe",
      "Perto do suporte o tempo todo, colado nele",
    ],
    correct: 2,
    explanation: "ADC fica atrás de tudo — você é de vidro e morre em 2 hits. Cause dano de longe e deixe o tank absorver o dano. Se você morrer primeiro, o time perde.",
  },
  {
    id: 44,
    category: "micro",
    difficulty: "bronze",
    question: "Você é o suporte no teamfight. Qual é sua prioridade?",
    options: [
      "Usar todo o dano possível no carry inimigo",
      "Proteger seu ADC e usar CC nos inimigos que ameaçam ele",
      "Ficar longe da luta para não morrer",
      "Engajar primeiro para surpreender o inimigo",
    ],
    correct: 1,
    explanation: "Suporte protege o carry aliado e usa CC para eliminar ameaças. Sua vida vale menos que a do ADC — troque a sua pela dele quando necessário.",
  },
  {
    id: 45,
    category: "micro",
    difficulty: "bronze",
    question: "Você é o tank/engager (ex: Malphite). Quando iniciar o teamfight?",
    options: [
      "Quando o inimigo avançar primeiro em você",
      "Somente após o ADC aliado dar o primeiro ataque",
      "Quando o time inimigo estiver agrupado e o seu time estiver pronto e próximo",
      "Logo que chegar perto — quanto mais rápido melhor",
    ],
    correct: 2,
    explanation: "Engage no momento certo: inimigos agrupados e seu time posicionado para seguir. Engajar sozinho sem o time perto é suicídio — espere todo mundo estar pronto.",
  },
  {
    id: 46,
    category: "macro",
    difficulty: "bronze",
    question: "Você é o mid laner e matou seu inimigo. O que fazer agora?",
    options: [
      "Ficar na mid farmando até o inimigo respawnar",
      "Rotar para bot ou top para criar pressão enquanto tem vantagem de número",
      "Ir direto para a base comprar itens",
      "Esperar na mid para matar o inimigo de novo quando ele voltar",
    ],
    correct: 1,
    explanation: "Mid é o centro do mapa — quando você está com vantagem, rode para outras lanes ou tome objetivos. Ficar parado na mid desperdiça a vantagem que você criou.",
  },
  {
    id: 47,
    category: "macro",
    difficulty: "bronze",
    question: "Você é o top laner e percebe que o inimigo da mid sumiu do mapa. O que fazer?",
    options: [
      "Continuar farmando — não é problema do top",
      "Recuar para perto da torre e avisar o time com ping de perigo",
      "Ir até a mid para verificar o que aconteceu",
      "Empurrar a wave rápido antes que o inimigo chegue",
    ],
    correct: 1,
    explanation: "Quando um inimigo some, qualquer lane pode ser o alvo. Recue, fique seguro e pingue para o time reagir. Continuar exposto é pedir para tomar um gank.",
  },
  {
    id: 48,
    category: "macro",
    difficulty: "bronze",
    question: "Você é o jungler e vê que seu aliado da bot está levando gank. O que fazer?",
    options: [
      "Continuar farmando a jungle — não consegue chegar a tempo",
      "Pingar para o aliado recuar e ignorar",
      "Verificar no mapa se você pode contra-gankar ou ajudar e ir se possível",
      "Ir ao Baron sozinho enquanto os inimigos estão na bot",
    ],
    correct: 2,
    explanation: "Avalie no mapa: se você está perto e pode ajudar, vá. Se não, veja se pode tomar um objetivo enquanto inimigos estão longe. Nunca ignore — sempre tome uma decisão ativa.",
  },
  {
    id: 49,
    category: "micro",
    difficulty: "bronze",
    question: "Você vai entrar no pit do Baron com o time. O que fazer ANTES de entrar?",
    options: [
      "Entrar direto — quanto mais rápido matar o Baron, melhor",
      "Esperar o Baron ficar com 50% de HP para entrar",
      "Colocar wards nas entradas e verificar a posição dos inimigos no mapa",
      "Enviar um jogador sozinho primeiro para verificar se está seguro",
    ],
    correct: 2,
    explanation: "Antes do Baron sempre ward as entradas — se o inimigo vir e você estiver preso no pit, você provavelmente perde o teamfight E o Baron. Visão é vida.",
  },
  {
    id: 50,
    category: "micro",
    difficulty: "bronze",
    question: "Você está numa luta 1v1 na lane e o inimigo está com muito mais HP. O que fazer?",
    options: [
      "All-in total — surpreender o inimigo pode funcionar",
      "Recuar, jogar seguro e esperar o jungler ou uma situação mais favorável",
      "Usar todos os summoner spells para tentar matar",
      "Parar de atacar e ficar parado esperando ele errar",
    ],
    correct: 1,
    explanation: "Nunca force uma luta desfavorável — recue e espere condições melhores. Uma morte grátis dá ouro e vantagem ao inimigo. Paciência é mecânica de Bronze que poucos têm.",
  },
  {
    id: 51,
    category: "objetivo",
    difficulty: "bronze",
    question: "Seu time está vencendo mas o inimigo tem um Tryndamere no splitpush. O que fazer?",
    options: [
      "Ignorar e focar no Dragon com o time todo",
      "Mandar um jogador defender enquanto o resto toma objetivos no outro lado",
      "Ir todos para matar o Tryndamere na lane dele",
      "Recuar todo o time para a base e esperar ele atacar",
    ],
    correct: 1,
    explanation: "Um bom splitpush cria um dilema: se o time todo for matar o splitpusher, ele foge. A solução é 1v1 com alguém que aguente e o resto aproveitar a vantagem numérica.",
  },
  {
    id: 52,
    category: "micro",
    difficulty: "bronze",
    question: "Como carry (ADC ou mago), quando você NUNCA deve engajar primeiro?",
    options: [
      "Quando o inimigo está com mais de 50% de HP",
      "Quando o jungler não está visível no mapa",
      "Quando você ainda não terminou o primeiro item",
      "Quando os tanks e engagers do seu time ainda não iniciaram",
    ],
    correct: 3,
    explanation: "Carry nunca entra primeiro — você morre instantaneamente. Espere o tank engajar e o inimigo gastar CC antes de entrar. Seu trabalho é estar vivo para causar dano.",
  },
  {
    id: 53,
    category: "micro",
    difficulty: "bronze",
    question: "Você é ADC e o assassino inimigo pulou em você. Qual a primeira coisa a fazer?",
    options: [
      "Usar o Flash para se afastar e criar distância",
      "Atacar ele para causar dano antes de morrer",
      "Chamar o suporte pelo microfone",
      "Usar ignite nele imediatamente",
    ],
    correct: 0,
    explanation: "Flash é sua sobrevivência — use para criar distância ou passar por trás do seu tank. O assassino gastou o engaje nele, agora o tank pode pegar a kill.",
  },
  {
    id: 54,
    category: "objetivo",
    difficulty: "bronze",
    question: "Falta 30 segundos para o Dragon nascer. Onde seu time deve estar?",
    options: [
      "Cada um farmando sua lane para chegar com mais ouro",
      "Juntando perto do Dragon com visão das entradas para contestar ou pegar seguro",
      "Fazendo Baron já que o Dragon ainda não nasceu",
      "Dando dive nas torres inimigas para criar pressão",
    ],
    correct: 1,
    explanation: "Agrupe perto do objetivo antes de nascer para não dar ao inimigo a chance de começar e stealar. Quem chega primeiro controla o pit.",
  },
  {
    id: 55,
    category: "macro",
    difficulty: "bronze",
    question: "Você está 0/5 na partida. Qual a melhor estratégia para ajudar o time?",
    options: [
      "Tentar fazer kills agressivas para recuperar o ouro perdido",
      "Jogar seguro, farmar, não arriscar mortes e seguir o time nas decisões",
      "Ficar na base esperando seu time resolver sozinho",
      "Mudar de rota e tentar uma lane diferente da que você estava",
    ],
    correct: 1,
    explanation: "Quando estiver morto, jogue safe — farm seguro, não force mortes, siga o time. Cada morte adicional faz o inimigo crescer ainda mais. Minimize o dano.",
  },
  {
    id: 56,
    category: "micro",
    difficulty: "bronze",
    question: "O que significa 'body block' ou 'interpor o corpo'?",
    options: [
      "Usar habilidades de empurrão para afastar inimigos",
      "Ficar na frente do seu carry para absorver skillshots ou dano no lugar dele",
      "Bloquear a passagem de minions com o seu campeão",
      "Usar o seu campeão para empurrar o inimigo para fora da lane",
    ],
    correct: 1,
    explanation: "Body block é se colocar entre o inimigo e seu carry para absorver habilidades ou dano. Suportes e tanks fazem isso para proteger o ADC em situações críticas.",
  },
  {
    id: 57,
    category: "objetivo",
    difficulty: "bronze",
    question: "Você ganhou um teamfight 5x0. Os inimigos têm 40 segundos de respawn. O que fazer?",
    options: [
      "Ir todos para a base para comprar itens com calma",
      "Esperar os inimigos respawnarem para dar outro teamfight",
      "Tomar o Baron ou torres, avançar com minions e pressionar o Nexus",
      "Cada um voltar para a sua lane para recuperar o CS perdido",
    ],
    correct: 2,
    explanation: "40 segundos de respawn é uma janela enorme — tome Baron, destrua torres, avance com minions e pressione o Nexus. Teamwipes existem para fechar o jogo, não para descansar.",
  },
];

// IDs fixos que todo mundo responde — sempre as mesmas 15 perguntas na mesma ordem
const FIXED_IDS = [3, 7, 9, 16, 17, 22, 26, 28, 33, 35, 37, 43, 45, 49, 52];

export function getFixedQuestions(): Question[] {
  return FIXED_IDS.map((id) => questions.find((q) => q.id === id)!);
}

export function getRandomQuestions(count: number = 10): Question[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export const categoryLabels: Record<Question["category"], string> = {
  campeao: "Campeões",
  macro: "Macro",
  micro: "Micro",
  itens: "Itens",
  objetivo: "Objetivos",
};
