export type Question = {
  id: number;
  category: "campeao" | "macro" | "micro" | "itens" | "objetivo";
  difficulty: "bronze";
  question: string;
  image?: string;
  options: string[];
  correct: number;
  explanation: string;
};

export const questions: Question[] = [
  // CAMPEÕES - ULTS
  {
    id: 1,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a ultimate do Galio faz?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg",
    options: [
      "Ele pula em cima de um aliado em qualquer lugar do mapa, causando dano em área",
      "Ele cria um escudo para todos os aliados",
      "Ele se transforma em pedra e vira invencível",
      "Ele invoca meteoros do céu",
    ],
    correct: 0,
    explanation: "Hero's Entrance: Galio voa até um aliado em qualquer lugar do mapa e cai com impacto, causando knock-up nos inimigos próximos.",
  },
  {
    id: 2,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a ultimate da Katarina?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg",
    options: [
      "Ela lança facas em linha reta",
      "Ela gira lançando facas em todos os inimigos próximos e pode ser interrompida com CC",
      "Ela se torna invisível por 5 segundos",
      "Ela invoca uma chuva de espadas do céu",
    ],
    correct: 1,
    explanation: "Death Lotus: Katarina gira rapidamente atirando facas em até 3 inimigos próximos. Qualquer CC a interrompe, então fique atento ao timing!",
  },
  {
    id: 3,
    category: "campeao",
    difficulty: "bronze",
    question: "O que o Malphite faz com a sua ultimate?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg",
    options: [
      "Ele cria um escudo de pedra",
      "Ele salta e ao cair causa knock-up em todos os inimigos da área",
      "Ele lança pedras em linha reta",
      "Ele aumenta o dano de todos os aliados",
    ],
    correct: 1,
    explanation: "Unstoppable Force: Malphite pula em alta velocidade em direção a um ponto causando knock-up massivo. É uma das melhores ults para iniciar teamfights!",
  },
  {
    id: 4,
    category: "campeao",
    difficulty: "bronze",
    question: "Qual é a passiva do Yasuo?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
    options: [
      "Ele ganha escudo quando toma dano",
      "Ele tem chance de acerto crítico dobrada e acumula uma barreira ao se mover",
      "Ele cura quando mata inimigos",
      "Ele ganha velocidade de ataque ao atacar",
    ],
    correct: 1,
    explanation: "Way of the Wanderer: Yasuo tem o bônus de crítico dobrado mas o item custa o dobro. Ele acumula escudo (Resolve) ao se mover.",
  },
  {
    id: 5,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a Lux faz com sua ultimate?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg",
    options: [
      "Ela cura todos os aliados próximos",
      "Ela dispara um raio de laser em linha reta causando muito dano",
      "Ela invoca um campo de luz que lentifica inimigos",
      "Ela se torna invisível",
    ],
    correct: 1,
    explanation: "Final Spark: Lux dispara um enorme laser que atravessa o mapa em linha reta. Tem alcance global e cooldown baixo com a passiva.",
  },
  {
    id: 6,
    category: "campeao",
    difficulty: "bronze",
    question: "O Zed é bom contra qual tipo de campeão?",
    options: [
      "Tanques com muito HP",
      "Magos de vidro (carries AP sem vida)",
      "Suportes com escudos",
      "ADCs com Thornmail",
    ],
    correct: 1,
    explanation: "Zed é um assassino AD que destrói magos e carries AP que não têm vida. Contra tanques ele é muito fraco!",
  },
  {
    id: 7,
    category: "campeao",
    difficulty: "bronze",
    question: "O que acontece quando você usa a Renata Glasc na ADC inimiga?",
    options: [
      "Ela cura a ADC inimiga",
      "Ela faz a ADC inimiga atacar os próprios aliados (Bait)",
      "Ela deixa a ADC invisível",
      "Ela troca posição com a ADC inimiga",
    ],
    correct: 1,
    explanation: "A ult da Renata (Hostile Takeover) faz os inimigos atacarem os próprios aliados. Se pegar a ADC inimiga, ela mata o próprio time!",
  },
  {
    id: 8,
    category: "campeao",
    difficulty: "bronze",
    question: "O Teemo coloca cogumelos invisíveis no mapa. Qual é a função principal deles?",
    options: [
      "Curar aliados que pisam neles",
      "Dar visão E envenenar inimigos que pisam neles",
      "Bloquear habilidades inimigas",
      "Aumentar a velocidade dos aliados",
    ],
    correct: 1,
    explanation: "Os cogumelos do Teemo (Noxious Trap) ficam invisíveis, dão visão da área e causam dano + lentidão nos inimigos que pisam. Ótimos para warding!",
  },

  // MACRO
  {
    id: 9,
    category: "macro",
    difficulty: "bronze",
    question: "Você acabou de matar o Dragon. O que você deve fazer LOGO EM SEGUIDA?",
    options: [
      "Voltar para a base imediatamente para comprar itens",
      "Empurrar a lane mais próxima ou o rift herald/torre enquanto tem vantagem numérica",
      "Ficar esperando o respawn do próximo objetivo",
      "Tentar dar dive no inimigo que está recuando",
    ],
    correct: 1,
    explanation: "Após pegar objetivo, você tem vantagem numérica pois os inimigos provavelmente morreram. Empurre uma torre, pegue herald ou force outro objetivo!",
  },
  {
    id: 10,
    category: "macro",
    difficulty: "bronze",
    question: "O que é 'push' em League of Legends?",
    options: [
      "Recuar para a torre",
      "Empurrar a wave de minions em direção à torre inimiga",
      "Chamar os aliados para teamfight",
      "Usar flash para fugir",
    ],
    correct: 1,
    explanation: "Push significa empurrar os minions em direção ao inimigo/torre. É importante para criar pressão de mapa e abrir espaço.",
  },
  {
    id: 11,
    category: "macro",
    difficulty: "bronze",
    question: "Qual objetivo dá uma vantagem global para o time quando morto?",
    options: [
      "Dragão",
      "Rift Herald",
      "Baron Nashor",
      "Torre",
    ],
    correct: 2,
    explanation: "Baron Nashor dá o buff Hand of Baron para todos os aliados vivos, fortalecendo os minions aliados. É o objetivo mais poderoso para fechar o jogo!",
  },
  {
    id: 12,
    category: "macro",
    difficulty: "bronze",
    question: "Você está sozinho na bot lane e vê que 2 inimigos desapareceram do mapa (missing). O que você faz?",
    options: [
      "Continua farmando normalmente",
      "Recua para a torre e avisa os aliados com ping",
      "Vai para o rio para verificar",
      "Tenta matar o inimigo que ainda está na lane",
    ],
    correct: 1,
    explanation: "Quando inimigos somem (missing/MIA), sempre recue para lugar seguro e use ping de danger/missing para avisar o time. Nunca continue exposto!",
  },
  {
    id: 13,
    category: "macro",
    difficulty: "bronze",
    question: "O que é 'recall' ou 'base' no contexto do jogo?",
    options: [
      "Usar uma habilidade de teleporte",
      "Voltar para a base para comprar itens e curar",
      "Recuar da luta",
      "Chamar o jungler",
    ],
    correct: 1,
    explanation: "Recall (B) faz você voltar para a base. Deve ser feito quando está com pouco HP/mana, tem dinheiro para item importante, ou a lane está empurrada com segurança.",
  },
  {
    id: 14,
    category: "macro",
    difficulty: "bronze",
    question: "O que é 'roaming' e quem normalmente faz isso?",
    options: [
      "Farmar todos os minions da lane, geralmente o ADC",
      "Sair da sua lane para ajudar outras lanes, geralmente mid ou support",
      "Defender a base, geralmente o tank",
      "Ficar na jungle matando monstros, qualquer campeão",
    ],
    correct: 1,
    explanation: "Roaming é quando um jogador abandona temporariamente a lane para criar pressão em outras partes do mapa. Mid e support são os melhores para isso.",
  },
  {
    id: 15,
    category: "macro",
    difficulty: "bronze",
    question: "Você tem 1500 de ouro mas o item que quer custa 3200. O que é melhor?",
    options: [
      "Ficar na lane sem voltar até juntar todo o ouro",
      "Comprar um componente barato agora e depois voltar quando tiver mais ouro",
      "Não comprar nada e guardar o ouro",
      "Vender itens que já tem para comprar o item caro imediatamente",
    ],
    correct: 1,
    explanation: "Sempre compre componentes para ter power spikes durante o jogo. Ficar sem item por muito tempo te deixa fraco sem motivo!",
  },

  // MICRO
  {
    id: 16,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'last hit' (CS)?",
    options: [
      "Causar o último hit em um campeão inimigo para matar",
      "Dar o último golpe em um minion para receber o ouro",
      "Usar a última habilidade disponível",
      "Atacar o inimigo pela última vez antes de recuar",
    ],
    correct: 1,
    explanation: "Last hit (CS = Creep Score) é dar o golpe final no minion para receber o ouro. É a base do farming e extremamente importante no early game!",
  },
  {
    id: 17,
    category: "micro",
    difficulty: "bronze",
    question: "Para que serve o Flash?",
    options: [
      "Causar dano em área",
      "Teleporte instantâneo de curto alcance para qualquer direção",
      "Tornar-se invencível por 1 segundo",
      "Curar 20% do HP máximo",
    ],
    correct: 1,
    explanation: "Flash é o summoner spell mais importante do jogo. Serve para escapar, iniciar, passar por paredes ou se reposicionar instantaneamente.",
  },
  {
    id: 18,
    category: "micro",
    difficulty: "bronze",
    question: "O que acontece se você fica parado perto de uma torre inimiga sem atacar?",
    options: [
      "Nada, a torre não ataca você",
      "A torre pode começar a te atacar se você estiver no range dela",
      "Você recebe buff de visão",
      "A torre te cura",
    ],
    correct: 1,
    explanation: "Torres atacam automaticamente inimigos que entram no seu alcance. Fique sempre fora do range da torre a menos que seja seguro avançar!",
  },
  {
    id: 19,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'kiting'?",
    options: [
      "Ficar parado atacando o inimigo",
      "Atacar e se mover alternadamente para manter distância enquanto causa dano",
      "Pular em cima do inimigo para iniciar a luta",
      "Usar habilidades de área em vários inimigos",
    ],
    correct: 1,
    explanation: "Kiting é atacar-mover-atacar para manter distância do inimigo. Essencial para ADCs e qualquer carry que precisa sobreviver enquanto causa dano.",
  },
  {
    id: 20,
    category: "micro",
    difficulty: "bronze",
    question: "Qual é a função principal do Ignite?",
    options: [
      "Curar o aliado mais próximo",
      "Causar dano ao longo do tempo e reduzir cura do inimigo para finalizar kills",
      "Criar uma barreira de fogo no mapa",
      "Aumentar o dano do próximo ataque",
    ],
    correct: 1,
    explanation: "Ignite causa dano true damage, aplica Grievous Wounds (reduz cura) e serve para finalizar inimigos que fugiriam com pouco HP. Ótimo para lanes agressivas!",
  },
  {
    id: 21,
    category: "micro",
    difficulty: "bronze",
    question: "O que é 'poke' em League of Legends?",
    options: [
      "Usar habilidades de curto alcance para iniciar luta",
      "Acertar habilidades de longo alcance no inimigo para desgastá-lo sem engajar completamente",
      "Chamar o jungler para fazer gank",
      "Dar last hit nos minions do inimigo",
    ],
    correct: 1,
    explanation: "Poke é desgastar o inimigo com habilidades de longo alcance sem se comprometer em uma luta completa. Campeões como Lux, Ezreal e Jayce são ótimos pokeurs.",
  },
  {
    id: 22,
    category: "micro",
    difficulty: "bronze",
    question: "Você está com 20% de HP na lane. Qual é a atitude certa?",
    options: [
      "Continuar atacando o inimigo pois você tem vantagem de CS",
      "Recuar para a torre ou fazer recall para não morrer de graça",
      "Tentar dar all-in no inimigo",
      "Pedir ao jungler para fazer gank imediatamente",
    ],
    correct: 1,
    explanation: "Com pouco HP você é um alvo fácil para gank e para o inimigo da lane. Sempre priorize sobrevivência — uma morte grátis dá ouro e vantagem ao inimigo!",
  },

  // ITENS
  {
    id: 23,
    category: "itens",
    difficulty: "bronze",
    question: "Qual é a função do item 'Thornmail'?",
    options: [
      "Aumentar o dano mágico",
      "Devolver dano físico para quem te ataca e aplicar Grievous Wounds",
      "Dar velocidade de movimento",
      "Curar o portador ao longo do tempo",
    ],
    correct: 1,
    explanation: "Thornmail reflete dano físico para quem te ataca corpo-a-corpo e aplica Grievous Wounds, reduzindo a cura do atacante. Perfeito contra ADCs e campeões de life steal!",
  },
  {
    id: 24,
    category: "itens",
    difficulty: "bronze",
    question: "Quando você deve comprar 'Grievous Wounds' (itens como Executioner's Calling ou Thornmail)?",
    options: [
      "Sempre no início do jogo como primeiro item",
      "Quando o inimigo tem muita cura (Soraka, Sylas, Dr. Mundo, etc.)",
      "Apenas quando você está perdendo a partida",
      "Somente suportes devem comprar",
    ],
    correct: 1,
    explanation: "Grievous Wounds reduz a cura em 40-60%. É essencial quando o time inimigo tem campeões com muita cura como Soraka, Mundo, Aatrox ou Sylas!",
  },
  {
    id: 25,
    category: "itens",
    difficulty: "bronze",
    question: "O que o item 'Rabadon's Deathcap' faz?",
    options: [
      "Aumenta o dano físico em 40%",
      "Aumenta o poder de habilidade (AP) total em 35%",
      "Dá cura por segundo",
      "Reduz o cooldown das habilidades",
    ],
    correct: 1,
    explanation: "Rabadon's aumenta TODO seu AP em 35%. É o item mais poderoso para magos no late game — construir ele faz seu dano explodir!",
  },

  // OBJETIVOS / LANE
  {
    id: 26,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que é um 'gank' do jungler?",
    options: [
      "O jungler voltar para a base para comprar itens",
      "O jungler sair da jungle para ajudar uma lane a matar um inimigo",
      "O jungler roubar os objetivos do inimigo",
      "O jungler ficar farmando camps na jungle",
    ],
    correct: 1,
    explanation: "Gank é quando o jungler visita uma lane para criar uma situação de superioridade numérica (2v1 ou 3v2) e tentar matar os inimigos da lane.",
  },
  {
    id: 27,
    category: "objetivo",
    difficulty: "bronze",
    question: "Qual é a diferença entre Dragon e Baron?",
    options: [
      "Nenhuma diferença, ambos dão o mesmo buff",
      "Dragon fica na metade inferior do mapa e dá buffs elementais acumuláveis; Baron fica na metade superior e dá buff de minion",
      "Dragon só pode ser atacado à noite, Baron durante o dia",
      "Dragon dá ouro e Baron dá XP",
    ],
    correct: 1,
    explanation: "Dragon (bot side) dá buffs elementais (Drake Souls). Baron (top side) dá Hand of Baron que fortalece minions. Ambos são cruciais mas em momentos diferentes do jogo!",
  },
  {
    id: 28,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que acontece quando você destrói o Nexus inimigo?",
    options: [
      "Você ganha o jogo imediatamente",
      "Você ganha mais ouro",
      "O inimigo perde uma vida",
      "O mapa muda de aparência",
    ],
    correct: 0,
    explanation: "Destruir o Nexus inimigo é O objetivo final do jogo. Assim que o Nexus cai, a partida termina com vitória para seu time!",
  },
  {
    id: 29,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que é 'freeze' de wave?",
    options: [
      "Congelar o mapa com habilidades de gelo",
      "Manter a wave de minions parada perto da sua torre para negar farm ao inimigo",
      "Empurrar rapidamente todos os minions",
      "Usar abilidades de slow nos inimigos",
    ],
    correct: 1,
    explanation: "Freeze é deixar a wave equilibrada bem perto da sua torre. O inimigo não consegue farmar sem se expor ao perigo da sua torre, criando forte pressão de lane!",
  },
  {
    id: 30,
    category: "objetivo",
    difficulty: "bronze",
    question: "O que significa 'splitpush'?",
    options: [
      "Dividir o time em dois grupos iguais",
      "Um jogador empurrar uma lane sozinho enquanto o time faz pressão em outra parte do mapa",
      "Fazer todos os jogadores atacarem a torre ao mesmo tempo",
      "Recuar todos para a base ao mesmo tempo",
    ],
    correct: 1,
    explanation: "Splitpush é quando um campeão forte (como Fiora, Tryndamere, Jax) empurra uma lane sozinho, forçando múltiplos inimigos a responder enquanto seu time pega objetivos.",
  },
  {
    id: 31,
    category: "campeao",
    difficulty: "bronze",
    question: "O que a Jinx faz de especial quando mata um campeão ou destrói um objetivo?",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
    options: [
      "Ela recua automaticamente para a base",
      "Ela fica com Get Excited: ganha grande boost de velocidade de movimento e ataque",
      "Ela ganha um escudo temporário",
      "Ela teleporta para o aliado mais próximo",
    ],
    correct: 1,
    explanation: "Get Excited! é a passiva da Jinx — ao participar de uma kill ou destruir objetivo, ela ganha enorme velocidade por alguns segundos. É por isso que ela é tão perigosa em teamfights quando começa a snowball!",
  },
  {
    id: 32,
    category: "macro",
    difficulty: "bronze",
    question: "Você e seu time acabaram de ganhar uma teamfight 5x5. O que é o ERRO mais comum de Bronze?",
    options: [
      "Ir imediatamente para o Baron ou torres",
      "Ficar dançando em cima dos cadáveres e esperar os inimigos respawnarem",
      "Fazer recall para comprar itens",
      "Iniciar outro teamfight imediatamente",
    ],
    correct: 1,
    explanation: "O erro mais clássico de Bronze é 'celebrate' — ficar parado comemorando após ganhar um teamfight em vez de converter a vantagem em objetivos. USE A VANTAGEM!",
  },
];

export function getRandomQuestions(count: number = 10): Question[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export const categoryLabels: Record<Question["category"], string> = {
  campeao: "Campeões",
  macro: "Macro",
  micro: "Micro",
  itens: "Itens",
  objetivo: "Objetivos",
};
